spring:
  boot:
    ws:
      host: 192.168.20.13
      port: 10081
      contextPath: /ws
      thread:
        bossThreadNum: 1
        workerThreadNum: 4
        monitorPeriodSec: 600
        heartBeatTimeSec: 60