spring:
  application:
    name: spring-boot-flux-ws
  redis:
    host: 192.168.60.103
    port: 6379
    # password: MjdkZTc2NTBlODA1NTJlOGY4
    timeout: 5000
    database: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tptest
    password: abc123
    url: jdbc:mysql://localhost:3306/docker_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
server:
  port: 8080
  # address: 192.168.20.13



