spring:
  application:
    name: spring-boot-flux-ws
  redis:
    host: 192.168.60.103
    port: 6379
    # password: MjdkZTc2NTBlODA1NTJlOGY4
    timeout: 5000
    database: 0
server:
  port: 9081
  address: 192.168.20.13

mq:
  kafka:
    consumer:
      brokerList: 192.168.60.103:9093,192.168.60.103:9094,192.168.60.103:9095
      autoCommit: true
      maxPoolNum: 100
      maxPoolTimeOut: 200
      workPoolQueueSize: 100
    produce:
      brokerList: 192.168.60.103:9093,192.168.60.103:9094,192.168.60.103:9095
      ack: all
      retries: 3
      linger: 20


