spring:
  application:
    name: spring-boot-content
  cloud:
    nacos:
      discovery:
        # 指定nacos server地址
        server-addr: localhost:8848
        ip: 192.168.20.13
        # 指定集群名称
        cluster-name: NJ
        metadata:
          version: 2.0
          target-version: 2.0
    sentinel:
      filter:
        # 关闭掉对spring mvc 端点的保护
        enabled: false
      transport:
        # 指定sentinel控制台地址
        dashboard: 192.168.20.13:8080
        clientIp: 192.168.20.13

server:
  port: 9999
  tomcat:
    max-threads: 20
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - sentinel
info:
  app-name: spring-boot-content
  author: 石头

ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 为哪些服务开启饥饿加载
    clients: spring-boot-user

logging:
  level:
    # 打开Feign日志级别，必须配置feign client的接口日志级别为debug
    com.ai.spring.boot.content.feignclient.UserServiceFeignClient: debug

feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: basic
      # 属性配置方法配置Feign日志级别
      spring-boot-user:
        # 开发环境使用full便于高度，生产环境使用basic
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient 做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  sentinel:
    enabled: true
## 配置文件方式配置负载均衡
#spring-boot-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


