spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.60.103:9093,192.168.60.103:9094,192.168.60.103:9095
          auto-create-topics: true
          producer-properties:
            - headerMode: raw
        bindings:
          output:
            destination: stream-demo
            content-type: text/plain